// shiori implications.js
// Generated 2026-05-31 from a Sonnet 4.6 fan-out over 17 reading-list papers.
// Each entry maps a paper id to two grounded implications (for Beacon a11y plugin
// and shikigarasu six-axis agent system), each with a verbatim quote and source
// location. shikigarasu.has === false means an honest "no clear implication" from
// that paper — five papers fall into this category (friston-2010, friston-2013,
// clark-2016, hohwy-2016, sunday-2023).
// Loaded as a global "paperImplications" object via <script src> before script.js.
// Edit the source of truth in vault: 4 BuildInPublic/shiori/implications.md
// and re-generate from _raw-implications.json.

const paperImplications = {
  "merleau-1945": {
    beacon: {
      has: true,
      text: "Merleau-Ponty shows that natural perception is always contextual and field-structured: an isolated feature is not how a perceiver actually encounters a problem. Beacon's current mode ('contrast 3.2:1 fails WCAG 1.4.3') reproduces what M-P calls analytic perception, which is artificial and non-natural. To trigger genuine recognition, Beacon should add a 'comparable case' alongside each finding: a real UI (screenshot or link) where the same failure appears in situ, so the reviewer perceives the accessibility gap as a whole situation rather than an abstract metric. This is not merely illustrative — M-P's argument is that the analytic breakdown of a phenomenon into isolated qualities actively conceals the very thing the reviewer is meant to judge. A case-based panel would restore the figure-ground structure that makes the problem legible without requiring the reviewer to re-synthesize it from first principles.",
      quote: "the perceived, by its nature, admits of the ambiguous, the shifting, and is shaped by its context. In Müller-Lyer's illusion, one of the lines ceases to be equal to the other without becoming 'unequal': it becomes 'different'. That is to say, an isolated, objective line, and the same line taken in a figure, cease to be, for perception, 'the same'. It is identifiable in these two functions only by analytic perception, which is not natural. In the same way the perceived contains gaps which are not mere 'failures to perceive'. I may, through sight or touch, recognize a crystal as having a 'regular' shape without having, even tacitly, counted its sides. I may be familiar with a face without ever having perceived the colour of the eyes in themselves.",
      where: "Chapter 1 ('The Sensation as a Unit of Experience'), pp. 13-14 (lines 1303-1313 of output.text-only.md)"
    },
    shikigarasu: {
      has: true,
      text: "Hakuso's 'Verdict + Findings + Required fixes' format lists each problem as an isolated quality attribute, which M-P identifies as the analytic attitude — artificial, non-natural, and prone to being accepted without genuine recognition. The same passage suggests that each finding only becomes perceptible as a real problem when placed in a context (a field) that gives it relational meaning. The concrete design change: each hakuso finding should be anchored to a prior case — 'this auth pattern is structurally identical to the bypass found in [case X]' or 'this N+1 query matches the pattern that caused degradation in [prior audit]' — so the reading agent perceives the failure as a situated figure against a known ground, not as an abstract rule violation. For seiran and shuen, the same principle applies differently: seiran recommendations that cite analogous strategic situations ('this is the positioning move that worked / failed in context Y') are perceived as options rather than pronouncements; shuen hypotheses anchored to a known failure mode are easier to challenge than free-floating 'blind spots'.",
      quote: "the perceived, by its nature, admits of the ambiguous, the shifting, and is shaped by its context. In Müller-Lyer's illusion, one of the lines ceases to be equal to the other without becoming 'unequal': it becomes 'different'. That is to say, an isolated, objective line, and the same line taken in a figure, cease to be, for perception, 'the same'. It is identifiable in these two functions only by analytic perception, which is not natural. In the same way the perceived contains gaps which are not mere 'failures to perceive'. I may, through sight or touch, recognize a crystal as having a 'regular' shape without having, even tacitly, counted its sides. I may be familiar with a face without ever having perceived the colour of the eyes in themselves.",
      where: "Chapter 1 ('The Sensation as a Unit of Experience'), pp. 13-14 (lines 1303-1313 of output.text-only.md)"
    }
  },
  "friston-2010": {
    beacon: {
      has: true,
      text: "Beacon's feature-based explanations (\"contrast 3.2:1 fails WCAG 1.4.3\") function as low-precision prediction errors: the rule engine resolves the mismatch immediately and the human reviewer has nothing left to update. Friston's precision-weighting mechanism predicts that \"prediction errors with high precision have a greater impact on units that encode conditional expectations\" — meaning a concrete, high-stakes example (a real lawsuit, a user recorded struggling, a site that lost a VPAT audit) would carry far more updating force than an abstract ratio-vs-threshold signal. Beacon should pair each failing score with a precision-boosting anchor: a documented real-world consequence that matches the failure category, displayed alongside the numeric score rather than buried in documentation. This shifts the reviewer's epistemic state from \"rule says fail\" (easily rubber-stamped) to \"this exact pattern cost site X $Y\" (a surprising case that must be reconciled with the reviewer's prior that their site is fine).",
      quote: "precision is important, especially in hierarchical schemes, because it controls the relative influence of bottom-up prediction errors and top-down predictions... prediction errors with high precision have a greater impact on units that encode conditional expectations.",
      where: "Section: Biased competition and attention (lines 1162-1169)"
    },
    shikigarasu: {
      has: false,
      text: "",
      quote: "",
      where: ""
    }
  },
  "friston-2013": {
    beacon: {
      has: true,
      text: "Beacon's feature-based output ('contrast 3.2:1 fails WCAG 1.4.3') functions as high-precision sensory evidence arriving in a reviewer who has weak prior beliefs about what genuine accessibility failure looks like — the paper predicts this causes the posterior judgment to be dominated almost entirely by the tool's signal, which is precisely the rubber-stamp dynamic. The fix the paper implies is not just adding examples for richness, but specifically for increasing the reviewer's prior precision: a concrete past case (a comparable site that was sued, a design pattern the reviewer's users will recognize) acts as an empirical prior that sharpens the reviewer's expectations before they weigh the metric. Beacon should therefore present case references not as supplementary context but as the precision-loading step that precedes the metric, making the reviewer's posterior a genuine weighted mixture of their own calibrated judgment and the WCAG signal, rather than a capitulation to whichever input arrived with higher apparent precision. In practice this means: show the analogous case first, let the reviewer form an expectation, then present the score — not score-first with a case bolted on.",
      quote: "the optimal combination of a prior belief with some evidence is a posterior belief whose mean is a mixture of the prior and data means, weighted according to their precision. If the precision of the data is overestimated, or if the precision of the prior is underestimated, the posterior expectation will shift from the prior mean to the data mean.",
      where: "Section introduction / Figure 1 caption context, lines 129-135"
    },
    shikigarasu: {
      has: false,
      text: "No actionable implication found. The paper's precision/prior framework describes pathological inference in biological neural systems — specifically how miscalibrated synaptic gain produces false beliefs. Mapping this to hakuso's output format (Verdict + Findings) would require the framework to say something about how human readers update beliefs when reading audit reports, which it does not. The resistance-to-rational-argument finding (lines 392-395) describes delusions arising from compensatory high-level belief precision in psychosis, not a general claim about how authoritative verdicts foreclose reconsideration in cognitively normal readers. Using this paper to argue for example-based hakuso verdicts would be analogy-by-label, not a genuine mechanistic connection.",
      quote: "",
      where: ""
    }
  },
  "hohwy-2013": {
    beacon: {
      has: true,
      text: "Beacon's feature-based explanations (\"contrast 3.2:1 fails WCAG 1.4.3\") are low-surprise inputs that reviewers' priors explain away with minimal engagement — a direct instance of what Hohwy calls low prediction-error gain leading to inference \"driven relatively more by prior expectations.\" Adding example-based explanations (\"this is the same low-contrast pattern that triggered DOJ action against Domino's in 2019\") functions as a high-precision, high-surprise signal that cannot be absorbed by the generic \"standard checklist item\" prior, forcing genuine hypothesis revision. Concretely: Beacon should offer an optional --case-mode flag that replaces the WCAG citation with a one-sentence real-world consequence (legal action, user abandonment metric, known lawsuit) alongside the technical finding. The case reference needs to be precise and specific — vague consequences (\"users may struggle\") will be treated as noise and gated down just like the current feature-based output.",
      quote: "When there is low gain on a prediction error, then the empirical prior expectations generating predictions will be weighted more in perceptual inference. For example, assume I am in a noisy or ambiguous situation where I don't expect to trust the incoming signal from the world much—a boisterous cocktail party, say. Assume also I cannot afford to dispense with inference, I must arrive at a perceptual conclusion (perhaps I am trying to maintain a conversation with someone I like). Then I'll give the sensory input little gain due to the noise, and perceptual inference will then be driven relatively more by prior expectations.",
      where: "Chapter 3, \"Prediction error, context, and precision\", section on prediction error gain (lines 3831-3841 in output.text-only.md)"
    },
    shikigarasu: {
      has: true,
      text: "Hakuso's structured verdict format (Verdict / Findings / Required fixes) creates the same prior-dominance trap: the recipient's model of \"what an audit looks like\" generates top-down predictions that explain away the specific findings before they are genuinely processed. Hohwy's framework suggests the fix is to raise prediction error gain at the point of contact — not by adding more findings, but by presenting one finding in a form the recipient's prior cannot anticipate. Concretely, hakuso should include a \"Closest prior failure\" field per critical finding: a named real case (internal or external) where the same pattern caused a measurable bad outcome. This works because specific named cases are epistemically harder to absorb as \"expected audit content\" — they are surprising relative to the recipient's prior and therefore receive higher effective gain. For the other axes, seiran (strategy) faces the same risk when its OST tree outputs are structurally predictable; varying the frame (e.g. leading with a falsifying question rather than a recommendation) would similarly raise prediction error gain on the strategy output.",
      quote: "Individuals who expect too much imprecision relative to the optimum—people who expect the world to be more noisy and uncertain than it is. They will tend to undersample the world, they will rely less on the senses and more readily rely on prior beliefs in arriving at estimates about the world. In short, such individuals will be more caught in an inner world than people with more optimal expected precisions.",
      where: "Chapter 7, \"Precarious prediction\", section \"Precisions, Sampling, and Prior Belief\" (lines 7598-7602 in output.text-only.md)"
    }
  },
  "clark-2016": {
    beacon: {
      has: true,
      text: "Beacon's feature-based explanations (\"contrast 3.2:1 fails WCAG 1.4.3\") function as low-precision error signals: they arrive without contextual grounding that raises the reader's confidence in their importance, so they are easily dismissed by existing priors (\"we've always done it this way,\" \"no one has complained\"). Clark's precision-weighting account predicts that abstract signals \"will have little or no influence upon ongoing processing and will fail to recruit or nuance higher level representations.\" An exemplar-based explanation (\"this is the same failure pattern as the Target accessibility lawsuit\" or \"Site X scoring 41 on this exact issue lost 18% of screen-reader users in user testing\") raises the assigned precision of the error signal by anchoring it to high-reliability, concrete evidence that the reader's prior model cannot easily explain away. Beacon should therefore add an optional exemplar layer to each finding: a real-world case, user-testing data point, or legal precedent that makes the mismatch between current state and expected state viscerally salient, not just technically correct.",
      quote: "very low-precision prediction errors will have little or no influence upon ongoing processing and will fail to recruit or nuance higher level representations.",
      where: "Ch. 5 (approx.), lines 5382-5383"
    },
    shikigarasu: {
      has: false,
      text: "No actionable connection found. Clark's book provides mechanistic neuroscience of hierarchical predictive processing; the rubber-stamping problem in hakuso outputs is an organizational/incentive problem (the reviewer has low stakes, weak feedback loops, or overloaded context) rather than a precision-weighting failure in the Clark sense. The book does not discuss auditing, structured reasoning outputs, or agent role design. Mapping \"verdict + findings\" onto \"top-down prior that suppresses error signals\" would stretch the analogy past usefulness: hakuso's reader is not a passive perceptual system but a goal-directed agent who can choose engagement level. A better frame for hakuso's rubber-stamp failure is decision theory or incentive design, not predictive processing.",
      quote: "",
      where: ""
    }
  },
  "hohwy-2016": {
    beacon: {
      has: true,
      text: "Beacon's current feature-based explanations (\"contrast 3.2:1 fails WCAG 1.4.3\") function as epistemically cheap inputs: they fit a reviewer's existing category model and generate minimal prediction error, so the EE-circle runs in its benign mode — the hypothesis is confirmed, nothing updates. The paper identifies that this same dynamic turns vicious when the evidence and hypothesis are mutually self-supporting with no independent challenge possible. Concretely, Beacon should introduce example-based findings not as a softer alternative but as a deliberate prediction-error injection: \"this button's contrast matches the pattern in the Domino's Pizza ADA settlement\" forces the reviewer's internal model to process a causal narrative with real-world stakes, which cannot be trivially assimilated into the prior \"rule violation\" category. The design implication is that examples should be selected for their capacity to generate surprise relative to the reviewer's expected frame — a lawsuit outcome, a user failure video, a screen-reader recording — not chosen for similarity to the current finding.",
      quote: "A system that minimizes prediction error is constantly tuning its hypotheses in response to the prediction error, where the prediction error essentially is a feedback signal received from the world in response to the brain's hypothesis-testing efforts. A PEM system is thus supervised directly by the truth.",
      where: "Section 4 (Inferential seclusion and scepticism), lines 429-432"
    },
    shikigarasu: {
      has: false,
      text: "The paper's prediction-error / EE-circle logic nominally applies to any structured output that generates low surprise in its reader, which would include Hakuso's Verdict + Findings format. However, this is the same mechanism already captured for Beacon and yields the same generic prescription (introduce example-based or case-based evidence to force genuine model-updating). The paper has no content specific to audit vs. exploration vs. strategy contexts, no mechanism that differentiates one axis from another, and no design constraint that would apply to Hakuso but not to Seiran or Shuen. Mapping the same PEM principle onto Hakuso would be re-labeling the Beacon implication, not deriving an additional one.",
      quote: "",
      where: ""
    }
  },
  "barrett-2017": {
    beacon: {
      has: true,
      text: "Barrett's experiments show that perception is not passive detection but active simulation from concepts: giving subjects a word list alongside a face photo dramatically raised accuracy because the words 'prompt the subjects to simulate facial configurations for the corresponding emotion concepts, preparing them to see certain emotions and not others.' Without an activated concept, the perceiver is 'experientially blind.' Applied to Beacon: a feature-based explanation ('contrast 3.2:1 fails WCAG 1.4.3') delivers a rule but not a concept — the reviewer checks the number and moves on. An example-based explanation ('this is like the button on Domino's that lost the Robles lawsuit') seeds a concrete instance that the reviewer then simulates in full, causing them to actively construct the accessibility failure rather than rubber-stamp a metric. Beacon should pair each finding with a named real-world case as a concept anchor alongside the feature reading, not instead of it — the case is what activates perception; the metric is what makes it verifiable.",
      quote: "The words not only limit the available choices but also prompt the subjects to simulate facial configurations for the corresponding emotion concepts, preparing them to see certain emotions and not others. This process is called priming.",
      where: "Chapter 3: The Myth of Universal Emotions (approx. p. 45), discussion of free-labeling vs. forced-choice experiments"
    },
    shikigarasu: {
      has: true,
      text: "Barrett argues that categorization is not feature-matching but goal-driven instance retrieval: 'When your brain needs a concept, it constructs one on the fly, mixing and matching from a population of instances from your past experience, to best fit your goals in a particular situation.' The 'winning instance' then determines behavior. Hakuso's current feature-based verdict format ('Verdict / Findings / Required fixes') presents findings as feature lists, which activate only a thin concept and generate a correspondingly thin remediation response — exactly the rubber-stamp failure. Two concrete changes follow: first, hakuso should append a past-case reference to each finding (e.g., 'similar to the auth-bypass in hakuso case #12-2025') so the auditor retrieves a rich instance that guides specific fixes rather than generic ones; second, hakuso should make audit goal explicit at the start ('goal: legal compliance' vs. 'goal: ship gate' vs. 'goal: user harm reduction') because the goal determines which winning instance is selected from memory and therefore which findings are actually surfaced — the same diff produces different critical findings depending on goal, and a goal-blind checklist cannot capture this.",
      quote: "When your brain needs a concept, it constructs one on the fly, mixing and matching from a population of instances from your past experience, to best fit your goals in a particular situation. And herein lies a key to understanding how emotions are made. Emotion concepts are goal-based concepts.",
      where: "Chapter 5: Concepts, Goals, and Words (approx. p. 92-93), goal-based concept section"
    }
  },
  "seth-2021": {
    beacon: {
      has: true,
      text: "Seth's controlled hallucination thesis directly challenges Beacon's current feature-based output format. When Beacon outputs 'contrast 3.2:1 fails WCAG 1.4.3', it produces a bottom-up sensory signal — but Seth argues that experience is determined by top-down predictions, not bottom-up signals, and that 'we never experience sensory signals themselves, we only ever experience interpretations of them.' A developer reading a raw metric will interpret it through their existing prior ('thresholds are arbitrary, I'll address it later'), which is exactly the rubber-stamping failure Beacon is trying to prevent. Example-based framing — 'this is the same contrast failure pattern as the Button Inc. lawsuit, where users with low vision couldn't activate the checkout CTA' — functions as a prediction error in Seth's sense: it is unexpected, contextually specific, and forces the existing prior to update rather than simply be confirmed. Beacon should offer example-based explanations as the primary layer, with the WCAG metric demoted to supporting evidence, because the prior (professional judgment) is updated by anomalous cases, not by threshold enumeration.",
      quote: "The third and most important ingredient in the controlled hallucination view is the claim that perceptual experience – in this case the subjective experience of 'seeing a coffee cup' – is determined by the content of the (top-down) predictions, and not by the (bottom-up) sensory signals. We never experience sensory signals themselves, we only ever experience interpretations of them.",
      where: "Part Two, 'The Wizard of Odds' / 'Perception as Controlled Hallucination' section, lines 3616-3622"
    },
    shikigarasu: {
      has: true,
      text: "Hakuso's 'Verdict + Findings + Required fixes' format is the audit equivalent of bottom-up feature detection: it enumerates raw signals (vulnerabilities, violations, anti-patterns) without engaging the reader's top-down belief system, which means strong priors ('this codebase is secure because we have tests') will simply absorb the findings rather than be updated by them. Seth describes this failure mode precisely: 'What we call hallucination is what happens when perceptual priors are unusually strong, overwhelming the sensory data so that the brain's grip on their causes in the world starts to slide.' A hakuso audit whose findings can be rationalized away by an already-confident team is functionally a hallucination suppressor — the team perceives 'review passed' regardless of what the findings actually say. The concrete design suggestion is to give hakuso an analog mode: for each severity-rated finding, optionally surface a precedent case or structural parallel ('this matches the pattern in the 2022 Log4Shell propagation — unexposed internal service, assumed-safe transitive dep') that generates genuine prediction error in the reviewer's prior. This applies to seiran and shuen as well: seiran recommendations that cite past failed strategic pivots, and shuen explorations that name prior blind spots from comparable systems, are more likely to update priors than abstract structural observations alone.",
      quote: "What we call 'hallucination' is what happens when perceptual priors are unusually strong, overwhelming the sensory data so that the brain's grip on their causes in the world starts to slide.",
      where: "Part Two, 'Controlled Hallucinations' / hallucination-as-strong-prior section, lines 5251-5255"
    }
  },
  "solms-2021": {
    beacon: {
      has: true,
      text: "Beacon's feature-based explanations (\"contrast 3.2:1 fails WCAG 1.4.3\") are processed in what Solms calls the automatic register: they are low-uncertainty signals the reviewer's predictive model already knows how to handle, so no affective arousal is generated and the response defaults to rubber-stamp reflex. An example-based explanation (\"this same pattern was at the center of the Target.com ADA lawsuit\") introduces a high-precision error signal that the reviewer's model did not predict, forcing the shift from automatic reflex to volitional deliberation that Solms describes as the gateway to voluntary behavior change. Concretely: Beacon should pair each finding with a real-world consequence case (lawsuit, user-reported failure, severity incident) placed immediately below the technical rule citation, not as an optional footnote. The affective valence of the real case — not the WCAG number — is what recruits conscious engagement.",
      quote: "The more your hypotheses are confirmed, the more confident you are, and the less aroused – less conscious – you need to be. You can automatise your action sequences and drift off into the default mode. But if you find yourself in an unexpected situation – one in which your predictive model appears to shed no reliable light – the consequences of your actions become highly salient. You switch out of autopilot and become hyper-aware: the decision triangle carefully adjusts your predictions as you feel your way through the consequences of your actions and make new choices.",
      where: "Chapter 9 / predictive hierarchy section (lines 5112-5120 of output.text-only.md)"
    },
    shikigarasu: {
      has: true,
      text: "Hakuso's current \"Verdict + Findings + Required fixes\" format operates as a low-uncertainty signal: reviewers already know the grammar of audit outputs, so the PAG assigns them low priority and they are processed automatically with minimal affective arousal, making rubber-stamp approval the path of least resistance. Solms's Law of Affect — that voluntary behavior is governed by felt consequences, not information transfer — suggests Hakuso should inject a felt-stakes layer into each severity-ranked finding: specifically, a concrete precedent (a past architectural decision that failed for this exact reason, or a known exploit class) that the reader could not predict from the technical description alone. This does not require Hakuso to maintain a case database itself; rather, the hakuso persona should be prompted to surface one real-world analogue per HIGH/CRITICAL finding before stating the verdict, converting abstract severity scores into affectively loaded error signals that demand voluntary engagement.",
      quote: "You decide what to do and what not to do on the basis of the felt consequences of your actions. This is the Law of Affect. Voluntary behaviour, guided by affect, thereby bestows an enormous adaptive advantage over involuntary behaviour: it liberates us from the shackles of automaticity and enables us to survive in unpredicted situations.",
      where: "Chapter 6 / Law of Affect section (lines 3537-3543 of output.text-only.md)"
    }
  },
  "clark-2023": {
    beacon: {
      has: true,
      text: "Beacon's feature-based explanations (\"contrast 3.2:1 fails WCAG 1.4.3\") are well-predicted by any developer who has reviewed accessibility reports before - the predictive brain signals only deviations from expectation, so familiar rule citations generate no prediction error and pass straight through to rubber-stamp approval. Example-based explanations break this by introducing a concrete prior the reader must actively match against their own UI: \"this button pattern resembles the one in the Target 2008 lawsuit\" forces a genuine comparison, generating prediction errors wherever the match is imperfect and the current case diverges. Practically: Beacon should pair each WCAG citation with one concrete anchor - a real case, a named site, a documented failure pattern - chosen to maximize mismatch with the generic expectation. The anchor need not be exhaustive; its function is to disrupt the \"well-predicted stuff\" that the brain discards without processing, not to serve as a legal reference.",
      quote: "For now, the point to notice is that in this kind of multilevel arrangement all that flows forward (from the sensory edges ever deeper into the brain) is news—deviations from what is expected. This is efficient. Valuable bandwidth is not used sending well-predicted stuff upward. Who in corporate HQ wants to know that Billie's work proceeded exactly as expected? Similarly in the neural incarnation, prediction errors at every level signal only the unexpected, the stuff that may plausibly demand further thought or action.",
      where: "Chapter 1 (Unboxing the Prediction Machine), lines 611-618"
    },
    shikigarasu: {
      has: true,
      text: "Hakuso's \"Verdict + Findings + Required fixes\" structure creates a high-confidence prior in the reader before they reach individual findings - the verdict label alone (\"PASS\" or \"CONDITIONAL\") seeds an expectation that then makes the supporting evidence feel confirmatory rather than investigative. Clark's research on spuriously self-confirming expectations shows this is not a reading failure but a feature of precision-weighted prediction: once a confident prior takes hold, new information is filtered through it and tends to reinforce rather than revise it. The fix is to delay the verdict until after the reader has been forced to engage with raw evidence - present the most anomalous or unexpected finding first (maximum prediction error), then the verdict as a conclusion rather than a frame. For other axes: seiran (strategy) should surface the most counter-intuitive scenario option first rather than leading with the recommended one, for the same reason - the recommendation label pre-collapses the decision space before the reader can form an independent prior.",
      quote: "Such studies suggest a complex dynamic in which false expectations, once they get a grip on us, become increasingly resistant to change. This phenomenon of spuriously self-confirming expectations is probably more common than we realize, as when a patient, expecting dentistry to hurt, experiences greater pain than they otherwise would—which then in turn appears to confirm, and thereby cements, their own prior belief.",
      where: "Chapter 2 (Psychiatry and Neurology: Closing the Gap), lines 1285-1289"
    }
  },
  "kk-2009": {
    beacon: {
      has: true,
      text: "Beacon's feature-based explanations (\"contrast 3.2:1 fails WCAG 1.4.3\") place reviewers in what K&K call a wicked learning environment: feedback on whether a fix actually prevented harm is delayed by months or years, so no genuine skill pattern develops and rubber-stamping fills the gap. The paper's NDM strand shows that skilled intuition requires an environment providing valid, recognizable cues tied to outcomes. Adding example-based explanations anchors each finding to a concrete prior outcome (e.g., a known complaint pattern, a documented user failure) and gives the reviewer a pattern to recognize rather than a rule to check off. Concretely: alongside the WCAG reference, Beacon should surface a brief case note such as \"this contrast ratio matches the modal failing pattern in X% of audited e-commerce checkouts where keyboard users abandoned\" — drawn from Beacon's own benchmark corpus. This transforms each score from a rule-check into a recognition cue, which is exactly the mechanism K&K identify as the foundation of genuine expertise.",
      quote: "Skilled intuitions will only develop in an environment of sufficient regularity, which provides valid cues to the situation... Without these opportunities to learn, a valid intuition can only be due to a lucky accident or to magic.",
      where: "Section \"Sources of Intuition\" / \"Conditions for Skilled Intuitions\", pp. 519-520 (lines 438-454 of output.text-only.md)"
    },
    shikigarasu: {
      has: true,
      text: "The paper's concept of fractionated expertise maps directly onto hakuso's risk: an audit axis issuing a single unified verdict implies uniform skill across all finding types, but K&K show that \"professionals who have expertise in some tasks are sometimes called upon to make judgments in areas in which they have no real skill\" and that this is a primary driver of overconfidence. Hakuso should tag each finding with a validity tier — high-validity domains (pattern-matching code smells, known injection vectors) versus low-validity domains (business logic correctness, UX judgment calls) — and apply different confidence calibration language accordingly. Additionally, K&K's endorsement of the premortem method is directly actionable: before hakuso issues its final verdict, it should run an internal \"what failure modes am I not seeing?\" pass (prospective hindsight), which K&K show generates more criticisms precisely because it suppresses the confidence that causes premature closure. This would structurally address the rubber-stamp problem without requiring example databases.",
      quote: "Professionals who have expertise in some tasks are sometimes called upon to make judgments in areas in which they have no real skill... It is difficult both for the professionals and for those who observe them to determine the boundaries of their true expertise.",
      where: "Section \"Fractionation of Expertise\" / Conclusions bullet on fractionated skill, p. 524 (lines 833-847 of output.text-only.md)"
    }
  },
  "noise-2021": {
    beacon: {
      has: true,
      text: "Beacon's current 0-100 absolute score is exactly the kind of absolute rating the book identifies as noise-prone: different reviewers interpreting the same number differently, no shared frame of reference. The book's prescription is a case scale where each score point is anchored to a concrete reference case, making the rating a relative judgment ('this button is like site X at score 42') rather than an abstract absolute one. Beacon should maintain a curated library of anchor sites at, say, five score bands (20, 40, 60, 80, 95), each with a named, real example and the specific issues that place it there. When Beacon scores a new component, it outputs 'score 38, comparable to [anchor site] at score 40 which also failed 1.4.3 on a primary CTA' — this forces the reviewer to do a comparison rather than rubber-stamp an opaque number, and it grounds the score in a shared reference class rather than an idiosyncratic internal scale.",
      quote: "With a case scale, each rating of a new individual is a comparison with the anchor cases. It becomes a relative judgment. Because comparative judgments are less susceptible to noise than ratings are, case scales are more reliable than scales that use numbers, adjectives, or behavioral descriptions.",
      where: "Chapter 23 (Performance Evaluations / Noise in Recurring Judgments), around line 9900"
    },
    shikigarasu: {
      has: true,
      text: "Hakuso's 'Verdict + Findings + Required fixes' format is an absolute rating on an implicit scale — reviewers bring their own severity thresholds, which is the core noise problem the book addresses. The book's mediating assessments protocol prescribes decomposing the judgment into independent sub-assessments scored before the holistic verdict is formed, and grounding each sub-assessment in a case scale anchored to reference examples. For hakuso, this means: (1) score each finding dimension (blast radius, exploitability, pattern frequency) separately before issuing the verdict, each anchored to a named reference case from past audits; (2) delay the 'Verdict' label until after those sub-scores are assembled; (3) the 'Required' vs 'Recommended' split should be calibrated against anchor cases, not left to in-context holistic impression. The same logic applies to seiran: a strategic recommendation framed as 'this positioning is like Option B in the [past project] case' forces comparative reasoning and surfaces the assumptions embedded in the score.",
      quote: "A practical way to do this is to create a case scale defined by anchor cases. You might say, for instance, that the target management team is 'as good as the management team of ABC Company when we acquired it' but not quite 'as good as the management team of DEF Company.' The anchor cases must, of course, be known to all the participants (and periodically updated). Defining them requires an up-front investment of time. But the value of this approach is that relative judgments (comparing this team to the ones at ABC and DEF) are much more reliable than are absolute ratings on a scale defined by numbers or adjectives.",
      where: "Chapter 26 (Mediating Assessments Protocol / recurring decisions section), around lines 10764-10772"
    }
  },
  "sunday-2023": {
    beacon: {
      has: true,
      text: "Beacon's current feature-based explanations (\"contrast 3.2:1 fails WCAG 1.4.3\") present each finding in isolation, giving the reviewer no calibration anchor. The paper argues that reliable judgment on novel cases requires first calibrating against familiar cases accessed independently: \"when calibrating intuition for fairness, one may take familiar cases and access them independently, mainly through discourse and analysis, to test the correctness of the intuitive data\" and that after each calibration step \"one may proceed to apply the method to new, similar cases by allowing slight parameter changes as compared with the cases by which the method was calibrated.\" Concretely, Beacon should surface one or two known reference cases alongside each finding: e.g., a previously resolved site that had the same contrast ratio and the actual outcome (passed audit, required fix, triggered legal action). This gives the reviewer a calibration baseline rather than an abstract rule, reducing the cognitive shortcut the paper calls a \"failure of cognitive heuristics\" — being misled into treating an unfamiliar case as a familiar, easier one. The example-based mode the question proposes is not just pedagogically nicer; it is the mechanism by which the paper argues reliable intuitive judgment becomes possible at all.",
      quote: "following each successful step in the calibration process, one may proceed to apply the method to new, similar cases by allowing slight parameter changes as compared with the cases by which the method was calibrated.",
      where: "Section 4 (Calibration of Intuition), lines 665-669"
    },
    shikigarasu: {
      has: false,
      text: "No specific, actionable implication for shikigarasu. The paper's sceptical ability framework (§6) describes a human's capacity to detect their own intuitive errors — it is a first-person cognitive skill developed through task-specific training and self-knowledge of one's biases. Hakuso's rubber-stamping problem is about an AI system's output format, not about a human failing to notice their own incorrect intuition. The calibration framework (§4) could in principle apply — surfacing precedent cases alongside verdicts — but the paper's calibration procedure is built around iterative discourse between two people checking each other's intuitions about particular cases, not around a system appending historical verdicts. Extending it to hakuso would require an inference the paper does not support. A generic recommendation to \"add examples\" does not flow from the paper's specific arguments.",
      quote: "",
      where: ""
    }
  },
  "bansal-2021": {
    beacon: {
      has: true,
      text: "Bansal et al. found that feature-based explanations (highlighting salient words, confidence scores) increased blind agreement with AI recommendations even when the AI was wrong — the very rubber-stamping failure Beacon faces with contrast-ratio citations. The paper's prescription is direct: 'Explanations should be informative, instead of just convincing' and the goal should be enabling users to 'quickly gauge through the explanation when the AI's reasoning is correct and when it should raise suspicion.' For Beacon, this supports replacing or augmenting single-verdict feature explanations with an adversarial mode: present the strongest counter-evidence alongside the finding (analogous to the paper's Adaptive Explain-Top-2 condition, which showed suggestive reductions in blind agreement). The paper also identifies timing as critical — showing AI findings before the user has formed their own assessment invokes the anchor effect; Beacon could mitigate this by requiring the user to rate an element before revealing the score, then showing disagreement-triggered detail rather than default explanation.",
      quote: "Explanations should be informative, instead of just convincing. Our current expert explanations did not help any more than the AI explanations, which may indicate that having the ML produce the maximally convincing explanation — a common objective shared in the design of many AI explanation algorithms — might be a poor choice for complementary performance. A more ideal goal is explanations that accurately inform the user – such that the user can quickly gauge through the explanation when the AI's reasoning is correct and when it should raise suspicion.",
      where: "Section 6.2 — Explaining AI for Appropriate Reliance"
    },
    shikigarasu: {
      has: true,
      text: "The paper establishes that feature-based explanations (the structure hakuso currently uses: Verdict + supporting findings) increase agreement with the AI's verdict regardless of correctness — users follow the output even when it errs. This validates the concern about rubber-stamping hakuso results. However, the paper does not test example-based (precedent-comparison) explanations, so it cannot confirm whether 'this resembles case X' would reduce over-reliance more than confidence-score or feature-highlight alternatives. What the paper does support concretely is that hakuso should incorporate a devil's-advocate mechanism: 'even if the system agrees with the user, the system can present a high-level summary of evidence for top-K alternatives and let the user drill down.' Applied to hakuso, this means after producing a verdict, explicitly surfacing the strongest arguments against that verdict — the best case for the opposite conclusion — before asking the reviewer to confirm. This is structurally different from example-based mode and more directly supported by the evidence.",
      quote: "instead of explaining why it believes an answer to be true, the AI might play a devil's advocate role, explaining its doubts — even when it agrees with the human. The doubts can even be expressed in an interactive fashion (as a back and forth conversation) than a set of static justifications, so to avoid cognitive overload. For example, even if the system agrees with the user, the system can present a high-level summary of evidence for top-K alternatives and let the user drill down, i.e., ask the system for more detailed evidence for the subset of alternatives that they now think are worth investigating.",
      where: "Section 6.2 — Explaining AI for Appropriate Reliance"
    }
  },
  "bucinca-2021": {
    beacon: {
      has: true,
      text: "Beacon's current feature-based output (\"contrast 3.2:1 fails WCAG 1.4.3\") is precisely the pattern the paper shows triggers rubber-stamping: explanations are read as a general competence signal rather than evaluated for content, so they increase trust and overreliance even when the AI is wrong. The paper's most actionable CFF for Beacon is the \"Update\" design: hide the score and fix suggestions by default, require the reviewer to record their own judgment first (\"does this element pass or fail?\"), then reveal Beacon's verdict alongside the explanation. The resulting disagreement triggers curiosity and analytical engagement, which is what the paper found most reliably reduced overreliance. The \"on demand\" variant — a collapsed panel the reviewer must click to expand — is a lighter version of the same mechanism and would be easier to ship first. Example-based explanations (\"like the button on site X that got sued\") are not tested in this paper and cannot be assessed from it, but the paper establishes that explanation format alone is insufficient without an interaction mechanism that forces engagement before the AI verdict is visible.",
      quote: "In the context of explainable AI, the implicit assumption behind the design of most systems is that people will engage analytically with each explanation and will use the content of these explanations to identify which of the AI's suggestions are plausible and which appear to be based on faulty reasoning. Because evaluating every explanation requires substantial cognitive effort, which humans are averse to, this assumption is likely incorrect. Instead, people appear to develop heuristics about the competence of the AI partner overall. Indeed, some studies demonstrate that explanations are interpreted as a general signal of competence—rather than being evaluated individually for their content—and just by their presence can increase the trust in and overreliance on the AI.",
      where: "Section 1 (Introduction), lines 88-96"
    },
    shikigarasu: {
      has: true,
      text: "Hakuso's current \"Verdict + Findings + Required fixes\" structure front-loads the AI judgment before the human engages, which the paper identifies as the root cause of rubber-stamping: reviewers read the verdict as a competence signal and skip analytical evaluation of individual findings. The paper's \"Update\" CFF maps directly to a hakuso redesign: before generating a verdict, prompt the requesting agent or human to state their own pre-assessment of the code/PR (\"what is your read of the risk here?\"), then reveal hakuso's findings and show where they diverge. The paper found this divergence-trigger — \"participants would be curious as to why the AI disagreed with their initial decision\" — was what drove genuine engagement. For seiran (strategy axis), the \"on demand\" variant applies: key assumptions or risk flags could be collapsed by default, requiring the user to click through before seeing the recommendation, creating a lightweight forcing moment. These are interaction-layer changes, not content changes — the paper's finding is that explanation quality matters less than whether the interaction design compels the human to form a judgment before consuming the AI output.",
      quote: "Participants in the update condition had to make the initial decision without the help of an AI (i.e., like in the no AI condition). Having made the initial decision, they were shown the AI's suggestion and explanation and could update their decision. We hypothesized that this condition would motivate the participants to engage with the explanation, especially when the AI disagreed with their initial decision. In other words, participants would be curious as to why the AI disagreed with them.",
      where: "Section 3.2.2 (Cognitive Forcing Functions — Update condition), lines 363-368"
    }
  },
  "chen-2023": {
    beacon: {
      has: true,
      text: "Beacon's current feature-based format (\"contrast 3.2:1 fails WCAG 1.4.3 — fix by adjusting color\") maps precisely onto what Chen et al. found increases overreliance: users scan scores rather than engage their own judgment, and the format provides no unreliability signal that would prompt them to question the finding. The paper shows example-based explanations achieved complementary human-AI performance by giving users two pathways feature-based formats block: (pathway 2) grounding feature reasoning in comparable real cases, and (pathway 3) exposing prediction unreliability when similar cases had mixed or wrong outcomes. Concretely, Beacon should add a comparator layer alongside each finding — e.g., \"three sites in this category with a similar button pattern scored below 60 on WCAG 2.1 keyboard tests; two later faced complaints\" — so the user can assess whether the current finding is high-confidence or borderline. The unreliability signal matters as much as the example itself: when comparator cases had mixed AI-prediction outcomes, Chen et al. found participants correctly overrode the AI; when all comparators were confidently correct, they followed it — exactly the calibration Beacon needs to move users from rubber-stamping to genuine triage.",
      quote: "feature-based explanations did not improve participants' decision outcomes compared to their performance without AI support, and led to overreliance on incorrect AI predictions. In contrast, example-based explanations reduced overreliance and helped achieve human-AI complementary performance — outperforming human or AI alone.",
      where: "Abstract / Section 4 Results (lines 99-103)"
    },
    shikigarasu: {
      has: true,
      text: "Hakuso's \"Verdict + Findings + Required fixes\" output is structurally identical to the feature-based explanation format Chen et al. found most prone to rubber-stamping: it presents scored or weighted evidence (severity labels, WCAG rule IDs, fix prescriptions) that reviewers can agree with without forming independent judgment, and it provides no signal about when the audit itself might be unreliable or near a borderline case. The paper's pathway 3 — recognizing unreliability through signals in the explanation — is the one that most reliably produced correct non-reliance; and the signal that worked best was when comparator examples showed the AI system had made incorrect predictions on similar past cases. For hakuso, this means adding a \"case similarity\" layer to findings: after each verdict, surface one or two past audit cases with analogous patterns and indicate whether hakuso's prior verdict on those was later confirmed or contested — effectively giving the summoner the \"both wrong\" signal that Chen et al. found prompted correct override. This is a concrete, addable output section, not a redesign: hakuso's existing Verdict/Findings/Required-fixes skeleton stays intact, and the example layer becomes a fourth block (\"Comparable cases\") that activates the summoner's pathway 2 and 3 reasoning rather than bypassing it.",
      quote: "example-based explanations provided strong signals of unreliability, particularly when the AI system predicts both examples incorrectly. These signals were not only accurate (highly correlated with AI incorrectness) but were also [strong enough to prompt correct non-reliance]",
      where: "Section 4.2 / pathway 3 analysis (lines 1222-1224)"
    }
  },
  "vasconcelos-2023": {
    beacon: {
      has: true,
      text: "Beacon's current feature-based explanation format (\"contrast 3.2:1 fails WCAG 1.4.3\") is precisely what this paper shows does NOT reduce overreliance: written explanations performed no better than prediction-only in easy and medium tasks, and clinicians in the paper's cited real-world case \"simply did not have time to engage with feature-based explanations\" and rubber-stamped instead. The paper's Study 3 demonstrates that the key variable is saliency: making the AI's error visually obvious at the point of failure drove overreliance to 0%, while written explanations left it unchanged. The concrete design implication for Beacon is to shift from prose descriptions of violations to inline visual markers on the rendered UI that flag the failing element directly — the equivalent of the paper's \"blue highlight at the wall crossing.\" The \"example-based\" direction (site X that got sued) is not what the paper validates; saliency of the error in-context is the lever.",
      quote: "In study 3, we validated that, the more salient an explanation makes an AI's mistake, the less overreliance there is... The salient explanation condition, our most most obvious explanation condition, has an average overreliance rate of 0%... a recent study found that clinicians simply did not have time to engage with feature-based explanations for individual patient predictions and instead requested evidence that the tool had been clinically validated.",
      where: "Study 3 summary (§7.4–7.6, Fig. 11, Table 4) and Limitations §10.4 'Different practitioners'"
    },
    shikigarasu: {
      has: true,
      text: "The paper predicts hakuso's current output format (structured text verdict + ranked findings) will be rubber-stamped by the engineer reading it, for the same reason written explanations underperform in easy tasks: when the verification cost exceeds the perceived benefit, humans default to accepting the AI's output. The paper's proposed remedy is saliency — make the error obvious at the point of failure — which is hard to achieve in hakuso's text-only output. However, the paper explicitly warns against the example-based direction you are considering: \"contrastive example-based explanations only provide users a rough understanding to the AI's biases and output. These do not necessarily tell users about the veracity of the AI's prediction.\" This means adding \"this is like case X\" annotations to hakuso output would not reduce rubber-stamping and may actually increase misplaced confidence. The actionable implication is narrower: hakuso should explicitly raise the perceived cost of wrongly accepting a verdict by requiring the reviewer to attest to specific findings before dismissal (a cognitive forcing function), rather than switching to example-based framing.",
      quote: "some explanations, such as Shapley Additive Explanations or contrastive example-based explanations, only provide users a rough understanding to the AI's biases and output. These do not necessarily tell users about the veracity of the AI's prediction... cognitive forcing functions decrease overreliance. We postulate that these forcing functions increase the cost of following the strategy to rely on the AI.",
      where: "§10.4 Limitations 'Explanation format' and §10.3 'Manipulating costs' item (1)"
    }
  }
};
